settings:
  bungee: false #If your server has anything to do with bungeecord, this being true will give you more placeholders
  showTitle: true #Shows title to panicking players, config below
  defaultCooldown: -1 #Set to -1 to have no cooldown, players with 'famedpanic.panic.cooldown.bypass' will bypass this cooldown
  allowStaffTeleport: true #This allows staff to teleport to panicking players through the /panicking command or the panic alert

  #THIS IS BETA WHICH MEANS THERE COULD BE ISSUES SURROUNDING ITS USE
  #This works by sending a player into vanish whilst in spectator mode
  #This plugin does not have player vanishing capabilities, you will need an external plugin
  #If you find any issues, please DM the plugin developer
  usePanicInspector:
    enabled: false
    vanishCommand: 'vanish' # Do not put the '/' at the start of this
    unvanishCommand: 'unvanish' # Do not put the '/' at the start of this
    secondsUntilRemoval: 10 #This is the delay between a player exiting panic mode, to that kicking their inspectors out of inspector mode. Set to -1 to stop automatic removing
    alertTarget: true #Sends alert.inspector-arrival to a panicking player once an inspector has arrived

panic:
  disableMovement: true #Stops player from being able to move
  interaction:
    stopOpening: true #Stops player from being able to open inventories (chests, furnaces, etc)
    stopDropping: true #*Stops player from being able to drop items
    stopPickup: true #*Stops player from being able to pick up items
    stopInventoryMoving: true #*Stops player from being able to move items in their inventory
    stopWorldInteraction: true #Stops player from being able to break/place/use blocks/items
    
  combat:
    stopDamager: true #Stops player from being able to deal damage (Some plugins may bypass this)
    stopDamagee: true #Stops player from being able to take damage
  stopCommands: #Stops player being able to use any of the following commands (WILL NOT STOP BUNGEE COMMANDS)
    - disabledcommandhere
  stopChat: false #Stops player being able to talk

title:
  title: '&c&lPANIC'
  subtitle: '&eA staff member will be with you shortly!'