settings:
  defaultCooldown: -1 #Set to -1 to have no cooldown

panic:
  disableMovement: true #Stops player from being able to move
  interaction:
    stopOpening: true #Stops player from being able to open inventories (chests, furnaces, etc)
    stopDropping: true #Stops player from being able to drop items
    stopPickup: true #Stops player from being able to pick up items
    stopInventoryMoving: true #Stops player from being able to move items in their inventory
    stopWorldInteraction: true #Stops player from being able to break/place/use blocks/items
    
  combat:
    stopDamager: true #Stops player from being able to deal damage (Some plugins may bypass this)
    stopDamagee: true #Stops player from being able to take damage
  stopCommands: #Stops player being able to use any of the following commands
    - disabledcommandhere
  stopChat: false #Stops player being able to talk