safemode: false #THIS MAY BE CHANGED BY THE PLUGIN - When true, panic alerts will not be sent to other services such as discord or slack
debug: false #This prints plugin operations for the developers to see where a version may be going wrong in sensitive areas

settings:
  bungee: false #If your server has anything to do with bungeecord, this being true will give you more placeholders
  showTitle: true #Shows title to panicking players, config below
  defaultCooldown: -1 #Set to -1 to have no cooldown, players with 'famedpanic.panic.cooldown.bypass' will bypass this cooldown (Time in seconds)
  allowStaffTeleport: true #This allows staff to teleport to panicking players through the /panicking command or the panic alert
  guis: #Some commands have the option to display GUIs for functionality, when this is false, no GUIs will be used
    enabled: true
    useBorder: true #A border is stained glass that covers the perimeter of the GUI, it has no functionality
    borderColor: 'red' #Sets the border (if above true) to the selected color (Options: white, orange, magenta, light blue, yellow, lime, pink, gray, light gray, cyan, purple, blue, brown, green, red, black)
    titleColor: 'red' #Sets all title text to the selected color (Options: black, dark blue, dark green, dark aqua, red, purple, gold, gray, dark gray, blue, green, aqua, red, light purple, yellow, white)
    defaultColor: 'gray' #Sets the default text to the selected color (Options: black, dark blue, dark green, dark aqua, red, purple, gold, gray, dark gray, blue, green, aqua, red, light purple, yellow, white)

  #THIS IS BETA WHICH MEANS THERE COULD BE ISSUES SURROUNDING ITS USE
  #This works by sending a player into vanish whilst in spectator mode
  #This plugin does not have player vanishing capabilities, you will need an external plugin
  #If you find any issues, please DM the plugin developer
  usePanicInspector:
    enabled: false
    vanishCommand: 'vanish' # Do not put the '/' at the start of this
    unvanishCommand: 'unvanish' # Do not put the '/' at the start of this
    secondsUntilRemoval: 10 #This is the delay between a player exiting panic mode, to that kicking their inspectors out of inspector mode. Set to -1 to stop automatic removing
    alertTarget: true #Sends alert.inspector-arrival to a panicking player once an inspector has arrived

panic:
  disableMovement: true #Stops player from being able to move
  interaction:
    stopOpening: true #Stops player from being able to open inventories (chests, furnaces, etc)
    stopDropping: true #*Stops player from being able to drop items
    stopPickup: true #*Stops player from being able to pick up items
    stopInventoryMoving: true #*Stops player from being able to move items in their inventory
    stopWorldInteraction: true #Stops player from being able to break/place/use blocks/items
    
  combat:
    stopDamager: true #Stops player from being able to deal damage (Some plugins may bypass this)
    stopDamagee: true #Stops player from being able to take damage
  stopCommands: #Stops player being able to use any of the following commands (WILL NOT STOP BUNGEE COMMANDS)
    - disabledcommandhere

title:
  title: '&c&lPANIC'
  subtitle: '&eA staff member will be with you shortly!'

api:
  enabled: false # When false, all API calls will be blocked
  canAccessTokens: false # When false, plugins will not be able to get your discord/slack authorisation settings
  canChangeSafemode: false  # When false, plugins will not be able to change safemode status
  canChangePanicking: false # When false, plugins will not be able to add or remove panicking players
  canChangeInspector: false # When false, plugins will not be able to change settings relating to the inspector

errors:
  deleteOldErrors: true # Deletes old error logs to stop too much storage being used
  daysUntilDeletion: 5 # Old logs will be deleted after this amount of days